receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}

processors:
  batch:
  attributes/update:
    actions:
      - key: http.request.header.authorization
        action: hash
      - key: http.request.header.x-data-token
        action: hash
      - key: http.request.header.x-management-key
        action: hash
  transform/host:
    metric_statements: &statements
      - context: resource
        statements:
          - set(attributes["host"], "otelcol-docker")
          - set(attributes["datadog.host.name"], "otelcol-docker")
    trace_statements: *statements # Use the same statements as in metrics
    log_statements:   *statements # Use the same statements as in metrics

connectors:
  datadog/connector:
    traces:
      compute_stats_by_span_kind: true
      peer_tags_aggregation: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/update, transform/host, batch]
      exporters: [datadog, datadog/connector]
    metrics:
      receivers: [otlp, datadog/connector]
      processors: [attributes/update, transform/host, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp]
      processors: [attributes/update, transform/host, batch]
      exporters: [datadog]
