extensions:
  basicauth/server:
    htpasswd:
      inline: |
        ${env:BASIC_AUTH_USERNAME}:${env:BASIC_AUTH_PASSWORD}

receivers:
  otlp/with-auth:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth/server

exporters:
  datadog:
    api:
      key: ${env:DD_API_KEY}
      site: ${env:DD_SITE}

processors:
  batch:
  attributes/update:
    actions:
      - key: http.request.header.authorization
        action: hash
      - key: http.request.header.x-data-token
        action: hash
      - key: http.request.header.x-management-key
        action: hash

connectors:
  datadog/connector:
    traces:
      compute_stats_by_span_kind: true
      peer_tags_aggregation: true

service:
  pipelines:
    traces:
      receivers: [otlp/with-auth]
      processors: [attributes/update, batch]
      exporters: [datadog, datadog/connector]
    metrics:
      receivers: [otlp/with-auth, datadog/connector]
      processors: [attributes/update, batch]
      exporters: [datadog]
    logs:
      receivers: [otlp/with-auth]
      processors: [attributes/update, batch]
      exporters: [datadog]
